### ISSUE TITLE
Tasks List for first run of monoloth prototype

### ISSUE THREAD

**Issue by saurabhpujar** [AICoE/Varangian#12]
Tasks for creation of monolith prototype and it's first run:

- [ ] Determine target projects
    - [x] Open GitHub issue in Varangian Repo [Saurabh]
    - [x] Issue 6 assigned to Ale, Christoph. PR: 4
    - [x] Examine some target projects [Yunhui]
    - [x] #16
    - [ ] #15 @zyh1121 
        - [ ] Grep
        - [ ] Crun
        - [ ] Fuse-overlayfs
        - [ ] https://github.com/containers/buildah/issues ?
- [ ] Training data split
    - [ ] Temporal slicing of commits into training, dev splits [Burn/Saurabh]
- [ ] Manual Verification of model output
- [ ] ML
    - [ ] Feature Engineering:
        - [x] Incorporate Yunchungs features in Feature Extractor [Burn]
        - [ ] Check if new features improve performance [Saurabh]
        - [ ] Add new features to feature extractor [Saurabh]
    - [x] Separate training and inference [Burn]
    - [x] Separate Voting from training [Burn]
- [ ] C-BERT:
    - [x] Create new train file for prototype [Luca]
    - [x] Create tokenization script [Saurabh]
    - [x] Inference mode tokenization[Luca/Saurabh]
    - [ ] Write script for artifacts package creation [Luca]
    - [ ] Run experiments to pick the right C-BERT model for prototype [Luca/Saurabh]
- [ ] Engineering
    - [x] Prepare system diagram [Saurabh]
    - [x] Formalize output across components [Saurabh/Burn/Luca]
    - [ ] Create Infer output code extractor [Burn] 
    - [ ] Write Python code for first run
    - [ ] Integration run
    - [ ] Model selector after training [Saurabh]
    - [ ] Inference output selector [Saurabh]
    - [ ] Get metrics at bug level
- [x] #13
    - [ ] Provide libtiff data to Kevin [Saurabh/Burn]
    - [ ] Bot Development @KPostOffice

**Comment by zyh1121** [comment]
* `https://github.com/containers/buildah/issues?`
Not an ideal project for now due to the static analyzer support. It's mainly in Go and Shell (Go 68.9%,  Shell 28.7%)

* In addition, the following two are the same thing, as the main efforts will be changes based on the released auto-labeler and dataset generator to support new heuristics. 
  - Generate auto-labeler data for #15 @zyh1121
  - Static Analyzer/Auto-labeler

* Since we are going to plan for multiple demos, is #15 still `priority/critical-urgent`

**Comment by saurabhpujar** [comment]
@zyh1121 

- Noted.
- Deleted duplicate task.
- We can discuss in the meeting today.
