### ISSUE TITLE
Determine a candidate list of projects for the initial run

### ISSUE THREAD

**Issue by saurabhpujar** [AICoE/Varangian#6]
There was some discussion on this during the last meeting. 

It was mentioned that we need a candidate list of projects which are:
1. Active and "healthy"
2. High number of users

Once we get the the candidate list, we can pick one most suited for differential analysis and begin.

Projects we worked with so far: Libtiff, Nginx, HTTPD, OpenSSL, Libav, FFMpeg

**Comment by zyh1121** [comment]
Perhaps we could start with some small or medium popular projects since it would take less time to finish the differential static analysis of their historical versions. 

How about some of the following projects?

* make - 2716 commits - https://git.savannah.gnu.org/cgit/make.git/log/
* grep - 2201 commits - https://git.savannah.gnu.org/cgit/grep.git/log/
* patch - 951 commits- https://git.savannah.gnu.org/cgit/patch.git/log/ 
* sed - 779 commits - https://git.savannah.gnu.org/cgit/sed.git/log/

**Comment by goern** [comment]
ja, I think thats a very good idea, @sub-mod ?

**Comment by sub-mod** [comment]
kindly add to https://github.com/AICoE/Varangian/pull/4

**Comment by saurabhpujar** [comment]
For the initial run in Milestone 2, the candidate was decided to be Libtiff. (#24 )

For Milestone 3, in addition to Libtiff we consider OpenSSL, FFMpeg, Grep, curn, fuse-overlayfs. (#29 )
